language: cpp

os:
  - osx

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - source build/SetupCI.sh

script: |
  ./build.sh -t Travis
