language: cpp

os:
  - linux
  - osx

dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y mono-devel; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install wget xz; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget -O mono.pkg http://download.mono-project.com/archive/nightly/macos-10-universal/MonoFramework-MDK-4.7.0.215.macos10.xamarin.universal.pkg; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo installer -pkg "mono.pkg" -target /; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then PREMAKE=premake5-linux-64; else PREMAKE=premake5-osx; fi &&
  external/CppSharp/build/$PREMAKE --file=build/premake5.lua gmake &&
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/Current/bin/; fi &&
  config=release make -C build/gmake/ &&
  TEST_RESULT=0 &&
  for test in build/gmake/lib/Release/*.Tests*; do $test || TEST_RESULT=$?; done &&
  exit "$TEST_RESULT"
