language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

install:
  - source build/SetupCI.sh

script: |
  ./build.sh -t Travis -v diagnostic
