# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

os: Visual Studio 2015

platform:
  - x86

configuration:
  - Release

#---------------------------------#
#    build scripts                #
#---------------------------------#

init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -t Generate-Android -v diagnostic
